//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Allocation_Info
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int Id { get; set; }
    	/// <summary>  
    	/// 分红单号  
    	/// </summary>
        public string Code { get; set; }
    	/// <summary>  
    	/// 开始时间  
    	/// </summary>
        public Nullable<System.DateTime> StartTime { get; set; }
    	/// <summary>  
    	/// 截至时间  
    	/// </summary>
        public Nullable<System.DateTime> EndTime { get; set; }
    	/// <summary>  
    	/// 总收入  
    	/// </summary>
        public Nullable<decimal> TotalAmount { get; set; }
    	/// <summary>  
    	/// 分配金额  
    	/// </summary>
        public Nullable<decimal> AllocationAmount { get; set; }
    	/// <summary>  
    	/// 会员数量  
    	/// </summary>
        public Nullable<int> MemberCount { get; set; }
    	/// <summary>  
    	/// 每位分配金额  
    	/// </summary>
        public Nullable<decimal> PerAmount { get; set; }
    	/// <summary>  
    	/// 操作时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>  
    	/// 操作人Id  
    	/// </summary>
        public string CreateEmpId { get; set; }
    	/// <summary>  
    	/// 操作人姓名  
    	/// </summary>
        public string CreateEmpName { get; set; }
    	/// <summary>  
    	/// 应发金额  
    	/// </summary>
        public Nullable<decimal> ShouldAmount { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> RealAmount { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string TypeName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Comment { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> PerAmount2 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> PerAmount3 { get; set; }
    }
}
