//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Bill_Info
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int BillId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> ProductId { get; set; }
    	/// <summary>  
    	/// 商品类别Id  
    	/// </summary>
        public Nullable<int> CategoryId { get; set; }
    	/// <summary>  
    	/// 商品类别名  
    	/// </summary>
        public string CategoryName { get; set; }
    	/// <summary>  
    	/// 商品名称  
    	/// </summary>
        public string ProductName { get; set; }
    	/// <summary>  
    	/// 规格型号  
    	/// </summary>
        public string ModelName { get; set; }
    	/// <summary>  
    	/// 原价  
    	/// </summary>
        public Nullable<decimal> OriginalPrice { get; set; }
    	/// <summary>  
    	/// 售价  
    	/// </summary>
        public Nullable<decimal> SalePrice { get; set; }
    	/// <summary>  
    	/// 浏览量  
    	/// </summary>
        public Nullable<decimal> PV { get; set; }
    	/// <summary>  
    	/// 库存数量  
    	/// </summary>
        public Nullable<int> Qty { get; set; }
    	/// <summary>  
    	/// 合计  
    	/// </summary>
        public Nullable<decimal> TotalPrice { get; set; }
    	/// <summary>  
    	/// 状态：未发货，已发货  
    	/// </summary>
        public string State { get; set; }
    	/// <summary>  
    	/// 会员Id  
    	/// </summary>
        public string MemberId { get; set; }
    	/// <summary>  
    	/// 会员编号  
    	/// </summary>
        public string MemberCode { get; set; }
    	/// <summary>  
    	/// 会员姓名  
    	/// </summary>
        public string NickName { get; set; }
    	/// <summary>  
    	/// 收货地址  
    	/// </summary>
        public string PostAddress { get; set; }
    	/// <summary>  
    	/// 联系电话  
    	/// </summary>
        public string Mobile { get; set; }
    	/// <summary>  
    	/// 下单时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>  
    	/// 发货时间  
    	/// </summary>
        public Nullable<System.DateTime> SendTime { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string ExpressName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string ExpressCode { get; set; }
    }
}
