//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class BNet_Info
    {
    	/// <summary>  
    	/// 主键  
    	/// </summary>
        public int Bid { get; set; }
    	/// <summary>  
    	/// 会员ID  
    	/// </summary>
        public string MemberId { get; set; }
    	/// <summary>  
    	/// 会员编码  
    	/// </summary>
        public string MemberCode { get; set; }
    	/// <summary>  
    	/// 会员昵称  
    	/// </summary>
        public string NickName { get; set; }
    	/// <summary>  
    	/// 上一级会员ID  
    	/// </summary>
        public string UpperId { get; set; }
    	/// <summary>  
    	/// 上一级会员编号  
    	/// </summary>
        public string UpperCode { get; set; }
    	/// <summary>  
    	/// 上一级会员昵称  
    	/// </summary>
        public string UpperNickName { get; set; }
    	/// <summary>  
    	/// 位置  
    	/// </summary>
        public string Position { get; set; }
    	/// <summary>  
    	/// 创建时间  
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    	/// <summary>  
    	/// 上级id  
    	/// </summary>
        public Nullable<int> PID { get; set; }
    	/// <summary>  
    	/// 网体类型,比如b,c,d,e网  
    	/// </summary>
        public int NetType { get; set; }
    }
}
