//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Fin_Convert
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int ConvertId { get; set; }
    	/// <summary>  
    	/// 会员Id  
    	/// </summary>
        public string MemberId { get; set; }
    	/// <summary>  
    	/// 会员编号  
    	/// </summary>
        public string MemberCode { get; set; }
    	/// <summary>  
    	/// 会员姓名  
    	/// </summary>
        public string NickName { get; set; }
    	/// <summary>  
    	/// 转账金额  
    	/// </summary>
        public Nullable<decimal> Amount { get; set; }
    	/// <summary>  
    	/// 转账类型：奖金转电子币  
    	/// </summary>
        public string ConvertType { get; set; }
    	/// <summary>  
    	/// 转账时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> Poundage { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> SAmount { get; set; }
    }
}
