//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Fin_Info
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int FinId { get; set; }
    	/// <summary>  
    	/// 会员Id  
    	/// </summary>
        public string MemberId { get; set; }
    	/// <summary>  
    	/// 会员编号  
    	/// </summary>
        public string MemberCode { get; set; }
    	/// <summary>  
    	/// 会员姓名  
    	/// </summary>
        public string NickName { get; set; }
    	/// <summary>  
    	/// 金额  
    	/// </summary>
        public Nullable<decimal> Amount { get; set; }
    	/// <summary>  
    	/// 互动奖  
    	/// </summary>
        public Nullable<decimal> Interaction { get; set; }
    	/// <summary>  
    	/// 手续费  
    	/// </summary>
        public Nullable<decimal> Poundage { get; set; }
    	/// <summary>  
    	/// 实发金额  
    	/// </summary>
        public Nullable<decimal> RealAmount { get; set; }
    	/// <summary>  
    	/// 转账类型：奖金转电子币  
    	/// </summary>
        public string TypeName { get; set; }
    	/// <summary>  
    	/// 摘要  
    	/// </summary>
        public string Comment { get; set; }
    	/// <summary>  
    	/// 相关会员Id  
    	/// </summary>
        public string RefMemberId { get; set; }
    	/// <summary>  
    	/// 相关会员编号  
    	/// </summary>
        public string RefMemberCode { get; set; }
    	/// <summary>  
    	/// 相关会员姓名  
    	/// </summary>
        public string RefNickName { get; set; }
    	/// <summary>  
    	/// 转账时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>  
    	/// 名品基金  
    	/// </summary>
        public Nullable<decimal> FamousBrandFund { get; set; }
    	/// <summary>  
    	/// 静态奖  
    	/// </summary>
        public Nullable<decimal> StaticBonus { get; set; }
    	/// <summary>  
    	/// 互助奖  
    	/// </summary>
        public Nullable<decimal> CooperationBonus { get; set; }
    	/// <summary>  
    	/// 是否已结算  
    	/// </summary>
        public Nullable<bool> IsSettlement { get; set; }
    	/// <summary>  
    	/// 结算时间  
    	/// </summary>
        public Nullable<System.DateTime> SettlementTime { get; set; }
    	/// <summary>  
    	/// 初始会员id，比如拿奖时的被激活会员  
    	/// </summary>
        public string StartMemberID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> CongXiao { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public int GroupDate { get; set; }
    }
}
