//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Fin_Transfer
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int TransferId { get; set; }
    	/// <summary>  
    	/// 转出会员Id  
    	/// </summary>
        public string FromMemberId { get; set; }
    	/// <summary>  
    	/// 转出会员编号  
    	/// </summary>
        public string FromMemberCode { get; set; }
    	/// <summary>  
    	/// 转出会员姓名  
    	/// </summary>
        public string FromNickName { get; set; }
    	/// <summary>  
    	/// 转入会员Id  
    	/// </summary>
        public string ToMemberId { get; set; }
    	/// <summary>  
    	/// 转入会员编号  
    	/// </summary>
        public string ToMemberCode { get; set; }
    	/// <summary>  
    	/// 转入会员姓名  
    	/// </summary>
        public string ToNickName { get; set; }
    	/// <summary>  
    	/// 转账金额  
    	/// </summary>
        public Nullable<decimal> Amount { get; set; }
    	/// <summary>  
    	/// 转账类型：电子币，佣金  
    	/// </summary>
        public string TransferType { get; set; }
    	/// <summary>  
    	/// 转账时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
