//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class GuiGeProduct_Info
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int GGId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> SName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string SComment { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> ProductId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> YouHui { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> LingShou { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> KuCun { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> YiShou { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> PeiHuo { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> YongJin1 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> YongJin2 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> TuiJian { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> DianZhu { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> ZC1 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> TJZC1 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> ZC2 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> TJZC2 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> ZC3 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> TJZC3 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> ZC4 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> TJZC4 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> ZC5 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> TJZC5 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> Sheng { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> Shi { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> Xian { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> ZhiTui { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> Scores { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> YSheng { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> YShi { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> YXian { get; set; }
    }
}
