//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class GuiGe_Info
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int GId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string GName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> PId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
