//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Logs
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 操作员ID  
    	/// </summary>
        public string EmpId { get; set; }
    	/// <summary>  
    	/// 操作员姓名  
    	/// </summary>
        public string EmpName { get; set; }
    	/// <summary>  
    	/// 事件  
    	/// </summary>
        public string Event { get; set; }
    	/// <summary>  
    	/// 描述  
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>  
    	/// 创建时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>  
    	/// IP地址  
    	/// </summary>
        public string IP { get; set; }
    	/// <summary>  
    	/// 浏览器  
    	/// </summary>
        public string Browser { get; set; }
    	/// <summary>  
    	/// 分辨率  
    	/// </summary>
        public string Screen { get; set; }
    	/// <summary>  
    	/// 操作系统  
    	/// </summary>
        public string OSVersion { get; set; }
    }
}
