//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Member_Info
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public string MemberId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Code { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string LoginPwd { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Pwd2 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Pwd3 { get; set; }
    	/// <summary>  
    	/// 推荐人Id  
    	/// </summary>
        public string RecommendId { get; set; }
    	/// <summary>  
    	/// 推荐人姓名  
    	/// </summary>
        public string RecommendName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string RecommendCode { get; set; }
    	/// <summary>  
    	/// 上级节点人Id  
    	/// </summary>
        public string UpperId { get; set; }
    	/// <summary>  
    	/// 上级节点名  
    	/// </summary>
        public string UpperName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string UpperCode { get; set; }
    	/// <summary>  
    	/// 位置，左1右2  
    	/// </summary>
        public string Position { get; set; }
    	/// <summary>  
    	/// 会员级别Id  
    	/// </summary>
        public Nullable<int> MemberLevelId { get; set; }
    	/// <summary>  
    	/// 会员级别名  
    	/// </summary>
        public string MemberLevelName { get; set; }
    	/// <summary>  
    	/// 昵称  
    	/// </summary>
        public string NickName { get; set; }
    	/// <summary>  
    	/// 性别  
    	/// </summary>
        public string Sex { get; set; }
    	/// <summary>  
    	/// 身份证号  
    	/// </summary>
        public string IdCode { get; set; }
    	/// <summary>  
    	/// 银行名  
    	/// </summary>
        public string BankName { get; set; }
    	/// <summary>  
    	/// 开户行  
    	/// </summary>
        public string OpenBank { get; set; }
    	/// <summary>  
    	/// 开户行地址  
    	/// </summary>
        public string BankAddress { get; set; }
    	/// <summary>  
    	/// 账户名  
    	/// </summary>
        public string BankAccount { get; set; }
    	/// <summary>  
    	/// 帐号  
    	/// </summary>
        public string BankCode { get; set; }
    	/// <summary>  
    	/// QQ  
    	/// </summary>
        public string QQ { get; set; }
    	/// <summary>  
    	/// 手机号  
    	/// </summary>
        public string Mobile { get; set; }
    	/// <summary>  
    	/// 收货地址  
    	/// </summary>
        public string PostAddress { get; set; }
    	/// <summary>  
    	/// 是否激活  
    	/// </summary>
        public string IsActive { get; set; }
    	/// <summary>  
    	/// 激活时间  
    	/// </summary>
        public Nullable<System.DateTime> ActiveTime { get; set; }
    	/// <summary>  
    	/// 激活金额  
    	/// </summary>
        public Nullable<decimal> ActiveAmount { get; set; }
    	/// <summary>  
    	/// 服务中心  
    	/// </summary>
        public string ServiceCenterId { get; set; }
    	/// <summary>  
    	/// 服务中心  
    	/// </summary>
        public string ServiceCenterCode { get; set; }
    	/// <summary>  
    	/// 是否是服务中心  
    	/// </summary>
        public string IsServiceCenter { get; set; }
    	/// <summary>  
    	/// 是否锁定  
    	/// </summary>
        public string IsLock { get; set; }
    	/// <summary>  
    	/// 奖金余额  
    	/// </summary>
        public Nullable<decimal> Commission { get; set; }
    	/// <summary>  
    	/// 累计奖金  
    	/// </summary>
        public Nullable<decimal> CommissionSum { get; set; }
    	/// <summary>  
    	/// 电子币余额  
    	/// </summary>
        public Nullable<decimal> Coins { get; set; }
    	/// <summary>  
    	/// 购物积分  
    	/// </summary>
        public Nullable<decimal> Scores { get; set; }
    	/// <summary>  
    	/// 已拿层奖层数  
    	/// </summary>
        public string Layered { get; set; }
    	/// <summary>  
    	/// 左区对碰余额  
    	/// </summary>
        public Nullable<decimal> LAmount { get; set; }
    	/// <summary>  
    	/// 右区对碰余额  
    	/// </summary>
        public Nullable<decimal> RAmount { get; set; }
    	/// <summary>  
    	/// 互动奖金余额  
    	/// </summary>
        public Nullable<decimal> InteractionAmount { get; set; }
    	/// <summary>  
    	/// 最后登录时间  
    	/// </summary>
        public Nullable<System.DateTime> LastLogin { get; set; }
    	/// <summary>  
    	/// 创建时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>  
    	/// 创建人Id  
    	/// </summary>
        public string CreateMemberId { get; set; }
    	/// <summary>  
    	/// 创建人名  
    	/// </summary>
        public string CreateMemberName { get; set; }
    	/// <summary>  
    	/// 名品基金  
    	/// </summary>
        public Nullable<decimal> FamousBrandFund { get; set; }
    	/// <summary>  
    	/// 是否锁定获得奖金，若True,则不可获得奖金  
    	/// </summary>
        public Nullable<bool> IsLockCommission { get; set; }
    	/// <summary>  
    	/// 是否锁定提现，若True：不可提现  
    	/// </summary>
        public Nullable<bool> IsLockDraw { get; set; }
    	/// <summary>  
    	/// 邮箱  
    	/// </summary>
        public string Email { get; set; }
    	/// <summary>  
    	/// 支付宝  
    	/// </summary>
        public string Alipay { get; set; }
    	/// <summary>  
    	/// 微信  
    	/// </summary>
        public string WeiXin { get; set; }
    	/// <summary>  
    	/// 是否子账号  
    	/// </summary>
        public Nullable<bool> IsSub { get; set; }
    	/// <summary>  
    	/// 父账号  
    	/// </summary>
        public string ParentId { get; set; }
    	/// <summary>  
    	/// 是否空激活  
    	/// </summary>
        public Nullable<bool> IsNullActive { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> ProvId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string ProvName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> CityId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string CityName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> CountyId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string CountyName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> TownId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string TownName { get; set; }
    	/// <summary>  
    	/// 分红累计  
    	/// </summary>
        public Nullable<decimal> FHSum { get; set; }
    	/// <summary>  
    	/// 推荐关系的位置 |分隔  
    	/// </summary>
        public string RPosition { get; set; }
    	/// <summary>  
    	/// 重消币  
    	/// </summary>
        public Nullable<decimal> CongXiao { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> ShopCoins { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> TourScores { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Photo { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> CommissionBan { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> FirstActive { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string OpenID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> StarLevel { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> AppellationLeveId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string AppellationLeveName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<bool> IsLockFen { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Shi { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Xian { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> ShengId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> ShiId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> XianId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Sheng { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string IsDL { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> DLId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string DLName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> ZCId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string ZCName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string DiZhi { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<double> JingDu { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<double> WeiDu { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string ShopName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string ShopImage { get; set; }
    }
}
