//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Member_Upgrade
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int UpgradeId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string MemberId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Code { get; set; }
    	/// <summary>  
    	/// 会员级别Id  
    	/// </summary>
        public Nullable<int> MemberLevelId { get; set; }
    	/// <summary>  
    	/// 会员级别名  
    	/// </summary>
        public string MemberLevelName { get; set; }
    	/// <summary>  
    	/// 会员级别Id  
    	/// </summary>
        public Nullable<int> NewMemberLevelId { get; set; }
    	/// <summary>  
    	/// 会员级别名  
    	/// </summary>
        public string NewMemberLevelName { get; set; }
    	/// <summary>  
    	/// 创建时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
