//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class ScoreRecord
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public decimal Scores { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public decimal Amount { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public int State { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string TradeNo { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Remark { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string MemberID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string MemberCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string MemberName { get; set; }
    }
}
