//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 商品支付方式  
    /// </summary>
    public partial class ShopProductPayway
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public long ID { get; set; }
    	/// <summary>  
    	/// 产品  
    	/// </summary>
        public Nullable<int> ProductID { get; set; }
    	/// <summary>  
    	/// 支付方式ID  
    	/// </summary>
        public Nullable<int> PaywayID { get; set; }
    	/// <summary>  
    	/// 支付方式名  
    	/// </summary>
        public string PaywayName { get; set; }
    
        public virtual ShopPayWay ShopPayWay { get; set; }
        public virtual ShopProduct ShopProduct { get; set; }
    }
}
