//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 一元云购  
    /// </summary>
    public partial class ShopOneBuy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopOneBuy()
        {
            this.ShopOneBuyDetails = new HashSet<ShopOneBuyDetail>();
        }
    
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 期号  
    	/// </summary>
        public string Code { get; set; }
    	/// <summary>  
    	/// 商品ID  
    	/// </summary>
        public int ProductID { get; set; }
    	/// <summary>  
    	/// 总需人次  
    	/// </summary>
        public int TotalCount { get; set; }
    	/// <summary>  
    	/// 参加人次  
    	/// </summary>
        public int Count { get; set; }
    	/// <summary>  
    	/// 支付方式  
    	/// </summary>
        public Nullable<int> PayWay { get; set; }
    	/// <summary>  
    	/// 添加时间  
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    	/// <summary>  
    	/// 是否启用  
    	/// </summary>
        public bool IsEnable { get; set; }
    	/// <summary>  
    	/// 是否完成  
    	/// </summary>
        public bool IsFinish { get; set; }
    	/// <summary>  
    	/// 完成时间  
    	/// </summary>
        public Nullable<System.DateTime> FinishTime { get; set; }
    	/// <summary>  
    	/// 获奖时间  
    	/// </summary>
        public Nullable<System.DateTime> WinTime { get; set; }
    	/// <summary>  
    	/// 获奖会员  
    	/// </summary>
        public string Winner { get; set; }
    	/// <summary>  
    	/// 获奖会员编号  
    	/// </summary>
        public string MemberCode { get; set; }
    	/// <summary>  
    	/// 获奖会员名  
    	/// </summary>
        public string NickName { get; set; }
    	/// <summary>  
    	/// 订单id  
    	/// </summary>
        public string OrderID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public int State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOneBuyDetail> ShopOneBuyDetails { get; set; }
        public virtual ShopOrder ShopOrder { get; set; }
        public virtual ShopPayWay ShopPayWay { get; set; }
        public virtual ShopProduct ShopProduct { get; set; }
    }
}
