//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 大转盘抽奖奖项  
    /// </summary>
    public partial class ShopBigWheelDetail
    {
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 活动ID  
    	/// </summary>
        public Nullable<int> BID { get; set; }
    	/// <summary>  
    	/// 名称  
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>  
    	/// 顺序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    	/// <summary>  
    	/// 描述  
    	/// </summary>
        public string Desc { get; set; }
    	/// <summary>  
    	/// 中奖概率  
    	/// </summary>
        public Nullable<decimal> Probability { get; set; }
    
        public virtual ShopBigWheel ShopBigWheel { get; set; }
    }
}
