//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 收货地址  
    /// </summary>
    public partial class ShopMyAddress
    {
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 会员ID  
    	/// </summary>
        public string MemberID { get; set; }
    	/// <summary>  
    	/// 收件人  
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>  
    	/// 电话  
    	/// </summary>
        public string Tel { get; set; }
    	/// <summary>  
    	/// 邮编  
    	/// </summary>
        public string PostCode { get; set; }
    	/// <summary>  
    	/// 省ID  
    	/// </summary>
        public Nullable<int> ProvId { get; set; }
    	/// <summary>  
    	/// 市ID  
    	/// </summary>
        public Nullable<int> CityID { get; set; }
    	/// <summary>  
    	/// 区ID  
    	/// </summary>
        public Nullable<int> CountyID { get; set; }
    	/// <summary>  
    	/// 省名  
    	/// </summary>
        public string ProvinceName { get; set; }
    	/// <summary>  
    	/// 市名  
    	/// </summary>
        public string CityName { get; set; }
    	/// <summary>  
    	/// 区名  
    	/// </summary>
        public string CountyName { get; set; }
    	/// <summary>  
    	/// 详细地址(不包含省市)  
    	/// </summary>
        public string Address { get; set; }
    	/// <summary>  
    	/// 是否默认  
    	/// </summary>
        public Nullable<bool> IsDefault { get; set; }
    	/// <summary>  
    	/// 排序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    	/// <summary>  
    	/// 添加时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
