//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 浏览记录  
    /// </summary>
    public partial class ShopBrowsingHistory
    {
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public long ID { get; set; }
    	/// <summary>  
    	/// 会员  
    	/// </summary>
        public string MemberID { get; set; }
    	/// <summary>  
    	/// 商品  
    	/// </summary>
        public int ProductID { get; set; }
    	/// <summary>  
    	/// 浏览时间  
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    
        public virtual ShopProduct ShopProduct { get; set; }
    }
}
