//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 快递公司  
    /// </summary>
    public partial class ShopExpress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopExpress()
        {
            this.ShopOrders = new HashSet<ShopOrder>();
        }
    
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 快递公司  
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>  
    	/// 编号  
    	/// </summary>
        public string Code { get; set; }
    	/// <summary>  
    	/// 描述  
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>  
    	/// 是否启用  
    	/// </summary>
        public bool IsEnable { get; set; }
    	/// <summary>  
    	/// 运费  
    	/// </summary>
        public Nullable<decimal> Postage { get; set; }
    	/// <summary>  
    	/// 物流网址  
    	/// </summary>
        public string HomePage { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrder> ShopOrders { get; set; }
    }
}
