//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 商品分类支付方式  
    /// </summary>
    public partial class ShopCategoryPayWay
    {
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 商品类别  
    	/// </summary>
        public Nullable<int> CategoryID { get; set; }
    	/// <summary>  
    	/// 支付方式ID  
    	/// </summary>
        public Nullable<int> PayWayID { get; set; }
    	/// <summary>  
    	/// 支付方式名  
    	/// </summary>
        public string PayWayName { get; set; }
    	/// <summary>  
    	/// 排序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    
        public virtual ShopPayWay ShopPayWay { get; set; }
    }
}
