//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 订单  
    /// </summary>
    public partial class ShopOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopOrder()
        {
            this.ShopOneBuys = new HashSet<ShopOneBuy>();
            this.ShopOrderProducts = new HashSet<ShopOrderProduct>();
            this.ShopOrderStates = new HashSet<ShopOrderState>();
            this.ShopOrderComments = new HashSet<ShopOrderComment>();
        }
    
    	/// <summary>  
    	/// GUID  
    	/// </summary>
        public string GUID { get; set; }
    	/// <summary>  
    	/// 订单号  
    	/// </summary>
        public string OrderCode { get; set; }
    	/// <summary>  
    	/// 流水号  
    	/// </summary>
        public string TraceNo { get; set; }
    	/// <summary>  
    	/// 会员ID  
    	/// </summary>
        public string MemberID { get; set; }
    	/// <summary>  
    	/// 会员编号  
    	/// </summary>
        public string MemberCode { get; set; }
    	/// <summary>  
    	/// 会员名字  
    	/// </summary>
        public string NickName { get; set; }
    	/// <summary>  
    	/// 商家ID  
    	/// </summary>
        public int ShopID { get; set; }
    	/// <summary>  
    	/// 支付方式  
    	/// </summary>
        public string PayWay { get; set; }
    	/// <summary>  
    	/// 支付状态,1：已支付  0：未支付  
    	/// </summary>
        public int PayState { get; set; }
    	/// <summary>  
    	/// 支付时间  
    	/// </summary>
        public Nullable<System.DateTime> PayTime { get; set; }
    	/// <summary>  
    	/// 快递编号  
    	/// </summary>
        public string ExpressCode { get; set; }
    	/// <summary>  
    	/// 快递公司  
    	/// </summary>
        public Nullable<int> ExpressID { get; set; }
    	/// <summary>  
    	/// 收货人  
    	/// </summary>
        public string Receiver { get; set; }
    	/// <summary>  
    	/// 发货地址  
    	/// </summary>
        public string PostAddress { get; set; }
    	/// <summary>  
    	/// 发货时间  
    	/// </summary>
        public Nullable<System.DateTime> PostTime { get; set; }
    	/// <summary>  
    	/// 收货人电话  
    	/// </summary>
        public string Tel { get; set; }
    	/// <summary>  
    	/// 邮费  
    	/// </summary>
        public Nullable<decimal> Postage { get; set; }
    	/// <summary>  
    	/// 留言备注  
    	/// </summary>
        public string Remark { get; set; }
    	/// <summary>  
    	/// 总价格  
    	/// </summary>
        public Nullable<decimal> TotalAmount { get; set; }
    	/// <summary>  
    	/// 订单状态  
    	/// </summary>
        public int State { get; set; }
    	/// <summary>  
    	/// 下单时间  
    	/// </summary>
        public System.DateTime SubmitTime { get; set; }
    	/// <summary>  
    	/// 优惠金额  
    	/// </summary>
        public Nullable<decimal> DiscountAmount { get; set; }
    	/// <summary>  
    	/// 实付金额  
    	/// </summary>
        public decimal RealAmount { get; set; }
    	/// <summary>  
    	/// 订单类型  
    	/// </summary>
        public string OrderType { get; set; }
    	/// <summary>  
    	/// 评价时间  
    	/// </summary>
        public Nullable<System.DateTime> PJTime { get; set; }
    	/// <summary>  
    	/// 完成时间  
    	/// </summary>
        public Nullable<System.DateTime> FinishTime { get; set; }
    	/// <summary>  
    	/// 退款时间  
    	/// </summary>
        public Nullable<System.DateTime> RefundTime { get; set; }
    	/// <summary>  
    	/// 取消时间  
    	/// </summary>
        public Nullable<System.DateTime> CancelTime { get; set; }
    	/// <summary>  
    	/// 实付购物币  
    	/// </summary>
        public decimal RealShopping { get; set; }
    	/// <summary>  
    	/// 实付重消币  
    	/// </summary>
        public decimal RealCongXiao { get; set; }
    	/// <summary>  
    	/// 实付积分  
    	/// </summary>
        public decimal RealScore { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string StoreCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string StoreName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string OperateCode { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public bool IsZiTi { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> ZongDay { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> YiDay { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Type { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> Count { get; set; }
    
        public virtual ShopExpress ShopExpress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOneBuy> ShopOneBuys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrderProduct> ShopOrderProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrderState> ShopOrderStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrderComment> ShopOrderComments { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
