//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 大转盘抽奖  
    /// </summary>
    public partial class ShopBigWheel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopBigWheel()
        {
            this.ShopBigWheelDetails = new HashSet<ShopBigWheelDetail>();
            this.ShopBigWheelLogs = new HashSet<ShopBigWheelLog>();
        }
    
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 活动标题  
    	/// </summary>
        public string Title { get; set; }
    	/// <summary>  
    	/// 描述  
    	/// </summary>
        public string Desc { get; set; }
    	/// <summary>  
    	/// 创建时间  
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    	/// <summary>  
    	/// 开始时间  
    	/// </summary>
        public Nullable<System.DateTime> StartTime { get; set; }
    	/// <summary>  
    	/// 截止日期  
    	/// </summary>
        public Nullable<System.DateTime> EndTime { get; set; }
    	/// <summary>  
    	/// 是否启用  
    	/// </summary>
        public bool IsEnable { get; set; }
    	/// <summary>  
    	/// 编号  
    	/// </summary>
        public string Code { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public bool IsDel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopBigWheelDetail> ShopBigWheelDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopBigWheelLog> ShopBigWheelLogs { get; set; }
    }
}
