//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 商城文章分类  
    /// </summary>
    public partial class ShopArticleCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopArticleCategory()
        {
            this.ShopArticles = new HashSet<ShopArticle>();
            this.ShopArticleCategorys = new HashSet<ShopArticleCategory>();
        }
    
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 类别名  
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>  
    	/// 上级类别  
    	/// </summary>
        public Nullable<int> PID { get; set; }
    	/// <summary>  
    	/// 是否首页底部导航栏目  
    	/// </summary>
        public bool IsIndexBottom { get; set; }
    	/// <summary>  
    	/// 级别  
    	/// </summary>
        public int Layer { get; set; }
    	/// <summary>  
    	/// 类型(0:普通，1:常见问题型)  
    	/// </summary>
        public int Type { get; set; }
    	/// <summary>  
    	/// 排序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopArticle> ShopArticles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopArticleCategory> ShopArticleCategorys { get; set; }
        public virtual ShopArticleCategory ShopArticleCategoryParent { get; set; }
    }
}
