//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 订单状态  
    /// </summary>
    public partial class ShopOrderState
    {
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 订单ID  
    	/// </summary>
        public string OrderID { get; set; }
    	/// <summary>  
    	/// 时间  
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    	/// <summary>  
    	/// 会员  
    	/// </summary>
        public string MemberID { get; set; }
    
        public virtual ShopOrder ShopOrder { get; set; }
    }
}
