//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 商家  
    /// </summary>
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.ShopAttentions = new HashSet<ShopAttention>();
            this.ShopOrders = new HashSet<ShopOrder>();
        }
    
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 商城名称  
    	/// </summary>
        public string ShopName { get; set; }
    	/// <summary>  
    	/// Logo  
    	/// </summary>
        public string Logo { get; set; }
    	/// <summary>  
    	/// 背景图  
    	/// </summary>
        public string Background { get; set; }
    	/// <summary>  
    	/// 电话  
    	/// </summary>
        public string Tel { get; set; }
    	/// <summary>  
    	/// 地址  
    	/// </summary>
        public string Address { get; set; }
    	/// <summary>  
    	/// 客服QQ  
    	/// </summary>
        public string QQ { get; set; }
    	/// <summary>  
    	/// 会员ID  
    	/// </summary>
        public string MemberID { get; set; }
    	/// <summary>  
    	/// 会员编号  
    	/// </summary>
        public string MemberCode { get; set; }
    	/// <summary>  
    	/// 会员名字  
    	/// </summary>
        public string NickName { get; set; }
    	/// <summary>  
    	/// 是否开启  
    	/// </summary>
        public bool IsEnable { get; set; }
    	/// <summary>  
    	/// 创建时间  
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    	/// <summary>  
    	/// 是否开启  
    	/// </summary>
        public bool IsCheck { get; set; }
    	/// <summary>  
    	/// 审核时间  
    	/// </summary>
        public Nullable<System.DateTime> CheckTime { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string ShopJingWeiD { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string WeiZhi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopAttention> ShopAttentions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrder> ShopOrders { get; set; }
    }
}
