//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 大转盘抽奖记录  
    /// </summary>
    public partial class ShopBigWheelLog
    {
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 活动ID  
    	/// </summary>
        public Nullable<int> BID { get; set; }
    	/// <summary>  
    	/// 抽奖人  
    	/// </summary>
        public string MemberID { get; set; }
    	/// <summary>  
    	/// 抽奖人Code  
    	/// </summary>
        public string MemberCode { get; set; }
    	/// <summary>  
    	/// 姓名  
    	/// </summary>
        public string NickName { get; set; }
    	/// <summary>  
    	/// 抽奖时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>  
    	/// 结果  
    	/// </summary>
        public string Result { get; set; }
    	/// <summary>  
    	/// 奖项  
    	/// </summary>
        public string Desc { get; set; }
    	/// <summary>  
    	/// 备注  
    	/// </summary>
        public string Remark { get; set; }
    	/// <summary>  
    	/// 结果ID  
    	/// </summary>
        public Nullable<int> ResultID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string IP { get; set; }
    
        public virtual ShopBigWheel ShopBigWheel { get; set; }
    }
}
