//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 商品分类  
    /// </summary>
    public partial class ShopProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopProductCategory()
        {
            this.ShopProducts = new HashSet<ShopProduct>();
            this.ShopProducts1 = new HashSet<ShopProduct>();
            this.ShopProductCategory1 = new HashSet<ShopProductCategory>();
        }
    
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 类别名  
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>  
    	/// Logo  
    	/// </summary>
        public string Logo { get; set; }
    	/// <summary>  
    	/// 描述  
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>  
    	/// 上级类别  
    	/// </summary>
        public Nullable<int> PID { get; set; }
    	/// <summary>  
    	/// 层级  
    	/// </summary>
        public int Layer { get; set; }
    	/// <summary>  
    	/// 顺序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopProduct> ShopProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopProduct> ShopProducts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopProductCategory> ShopProductCategory1 { get; set; }
        public virtual ShopProductCategory ShopProductCategory2 { get; set; }
    }
}
