//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 幻灯片  
    /// </summary>
    public partial class ShopSlide
    {
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 名称  
    	/// </summary>
        public string Title { get; set; }
    	/// <summary>  
    	/// 图片  
    	/// </summary>
        public string Img { get; set; }
    	/// <summary>  
    	/// 链接地址  
    	/// </summary>
        public string Link { get; set; }
    	/// <summary>  
    	/// 排序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    	/// <summary>  
    	/// 描述  
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> Type { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Video { get; set; }
    }
}
