//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 支付方式  
    /// </summary>
    public partial class ShopPayWay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopPayWay()
        {
            this.ShopCategoryPayWays = new HashSet<ShopCategoryPayWay>();
            this.ShopOneBuys = new HashSet<ShopOneBuy>();
            this.ShopProductPayways = new HashSet<ShopProductPayway>();
        }
    
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 支付方式1  
    	/// </summary>
        public string PayWay { get; set; }
    	/// <summary>  
    	/// 顺序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    	/// <summary>  
    	/// 是否默认显示  
    	/// </summary>
        public bool IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCategoryPayWay> ShopCategoryPayWays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOneBuy> ShopOneBuys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopProductPayway> ShopProductPayways { get; set; }
    }
}
