//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 商品  
    /// </summary>
    public partial class ShopProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopProduct()
        {
            this.ShopBrowsingHistories = new HashSet<ShopBrowsingHistory>();
            this.ShopCats = new HashSet<ShopCat>();
            this.ShopCollectionProducts = new HashSet<ShopCollectionProduct>();
            this.ShopOneBuys = new HashSet<ShopOneBuy>();
            this.ShopOrderProducts = new HashSet<ShopOrderProduct>();
            this.ShopProductPayways = new HashSet<ShopProductPayway>();
            this.ShopProductImages = new HashSet<ShopProductImage>();
        }
    
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 主标题  
    	/// </summary>
        public string Title { get; set; }
    	/// <summary>  
    	/// 副标题  
    	/// </summary>
        public string SubTitle { get; set; }
    	/// <summary>  
    	/// 原价  
    	/// </summary>
        public decimal PriceOriginal { get; set; }
    	/// <summary>  
    	/// 会员价  
    	/// </summary>
        public decimal PriceVip { get; set; }
    	/// <summary>  
    	/// 购物币  
    	/// </summary>
        public decimal PriceShopping { get; set; }
    	/// <summary>  
    	/// 重消币  
    	/// </summary>
        public decimal PriceCongXiao { get; set; }
    	/// <summary>  
    	/// 积分  
    	/// </summary>
        public decimal PriceScore { get; set; }
    	/// <summary>  
    	/// 商品类别  
    	/// </summary>
        public Nullable<int> CategoryID { get; set; }
    	/// <summary>  
    	/// 是否上架  
    	/// </summary>
        public bool IsEnable { get; set; }
    	/// <summary>  
    	/// 是否最新  
    	/// </summary>
        public bool IsNew { get; set; }
    	/// <summary>  
    	/// 是否热点  
    	/// </summary>
        public bool IsHot { get; set; }
    	/// <summary>  
    	/// 是否推荐  
    	/// </summary>
        public bool IsRecommend { get; set; }
    	/// <summary>  
    	/// 库存  
    	/// </summary>
        public int Inventory { get; set; }
    	/// <summary>  
    	/// 邮费  
    	/// </summary>
        public decimal Postage { get; set; }
    	/// <summary>  
    	/// 排序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    	/// <summary>  
    	/// 商品简介  
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>  
    	/// 详细描述  
    	/// </summary>
        public string Content { get; set; }
    	/// <summary>  
    	/// 商家  
    	/// </summary>
        public int ShopID { get; set; }
    	/// <summary>  
    	/// 添加时间  
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    	/// <summary>  
    	/// 修改时间  
    	/// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
    	/// <summary>  
    	/// 主图  
    	/// </summary>
        public string Image { get; set; }
    	/// <summary>  
    	/// 销量  
    	/// </summary>
        public int Sales { get; set; }
    	/// <summary>  
    	/// 品牌  
    	/// </summary>
        public Nullable<int> BrandID { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public decimal PV { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> CategoryID1 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public bool IsPotagte { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public int PraiseCount { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Activity { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> YongJin1 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> YongJin2 { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<decimal> TuiJian { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string CanTuanBiLi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopBrowsingHistory> ShopBrowsingHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCat> ShopCats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCollectionProduct> ShopCollectionProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOneBuy> ShopOneBuys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrderProduct> ShopOrderProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopProductPayway> ShopProductPayways { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopProductImage> ShopProductImages { get; set; }
        public virtual ShopProduct ShopProduct1 { get; set; }
        public virtual ShopProduct ShopProduct2 { get; set; }
        public virtual ShopProductCategory ShopProductCategory { get; set; }
        public virtual ShopProductCategory ShopProductCategory1 { get; set; }
    }
}
