//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 导航  
    /// </summary>
    public partial class ShopNavigation
    {
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 导航名称  
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>  
    	/// 描述  
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>  
    	/// 导航类型0：主导航，1:底部  
    	/// </summary>
        public int Type { get; set; }
    	/// <summary>  
    	/// 链接地址  
    	/// </summary>
        public string URL { get; set; }
    	/// <summary>  
    	/// 打开方式  
    	/// </summary>
        public string Target { get; set; }
    	/// <summary>  
    	/// 顺序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    	/// <summary>  
    	/// 是否启用  
    	/// </summary>
        public bool IsEnable { get; set; }
    }
}
