//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 商品相册  
    /// </summary>
    public partial class ShopProductImage
    {
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 商品ID  
    	/// </summary>
        public int ProductID { get; set; }
    	/// <summary>  
    	/// 图片地址  
    	/// </summary>
        public string URL { get; set; }
    	/// <summary>  
    	/// 缩略图地址  
    	/// </summary>
        public string ThumURL { get; set; }
    	/// <summary>  
    	/// 顺序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    	/// <summary>  
    	/// 文件Hash码  
    	/// </summary>
        public string HashCode { get; set; }
    	/// <summary>  
    	/// 上传时间  
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
    	/// <summary>  
    	/// 上传人  
    	/// </summary>
        public string MemberID { get; set; }
    	/// <summary>  
    	/// 描述  
    	/// </summary>
        public string Description { get; set; }
    
        public virtual ShopProduct ShopProduct { get; set; }
    }
}
