//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 品牌  
    /// </summary>
    public partial class ShopBrand
    {
    	/// <summary>  
    	/// ID  
    	/// </summary>
        public int ID { get; set; }
    	/// <summary>  
    	/// 品牌名  
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>  
    	/// Logo  
    	/// </summary>
        public string Logo { get; set; }
    	/// <summary>  
    	/// 品牌简介  
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>  
    	/// 是否推荐  
    	/// </summary>
        public bool IsRecommend { get; set; }
    	/// <summary>  
    	/// 是否国际  
    	/// </summary>
        public bool IsWorld { get; set; }
    	/// <summary>  
    	/// 顺序  
    	/// </summary>
        public Nullable<int> Sort { get; set; }
    	/// <summary>  
    	/// 所属大类  
    	/// </summary>
        public Nullable<int> CategoryID { get; set; }
    }
}
