//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Sys_BasicData
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int Id { get; set; }
    	/// <summary>  
    	/// 字典类型  
    	/// </summary>
        public Nullable<int> TypeId { get; set; }
    	/// <summary>  
    	/// 字典名称  
    	/// </summary>
        public string BasicDataName { get; set; }
    	/// <summary>  
    	/// 排序  
    	/// </summary>
        public Nullable<int> SortValue { get; set; }
    }
}
