//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Sys_Employee
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public string EmpId { get; set; }
    	/// <summary>  
    	/// 登陆名  
    	/// </summary>
        public string LoginName { get; set; }
    	/// <summary>  
    	/// 密码  
    	/// </summary>
        public string Password { get; set; }
    	/// <summary>  
    	/// 真实姓名  
    	/// </summary>
        public string RealName { get; set; }
    	/// <summary>  
    	/// 性别  
    	/// </summary>
        public string Sex { get; set; }
    	/// <summary>  
    	/// 手机号  
    	/// </summary>
        public string Mobile { get; set; }
    	/// <summary>  
    	/// 部门编号  
    	/// </summary>
        public Nullable<int> DepartmentId { get; set; }
    	/// <summary>  
    	/// 职位编号  
    	/// </summary>
        public Nullable<int> PositionId { get; set; }
    	/// <summary>  
    	/// 角色编号  
    	/// </summary>
        public Nullable<int> RoleId { get; set; }
    	/// <summary>  
    	/// 状态：在职，离职  
    	/// </summary>
        public string EmpState { get; set; }
    	/// <summary>  
    	/// 备注  
    	/// </summary>
        public string Comment { get; set; }
    	/// <summary>  
    	/// 上次登录时间  
    	/// </summary>
        public Nullable<System.DateTime> LastLogin { get; set; }
    }
}
