//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    ///   
    /// </summary>
    public partial class Sys_Msg
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public int MsgId { get; set; }
    	/// <summary>  
    	/// 类型：订单处理  
    	/// </summary>
        public string MsgType { get; set; }
    	/// <summary>  
    	/// 发送者Id  
    	/// </summary>
        public string SenderId { get; set; }
    	/// <summary>  
    	/// 发送人编号  
    	/// </summary>
        public string SenderCode { get; set; }
    	/// <summary>  
    	/// 发送者姓名  
    	/// </summary>
        public string SenderName { get; set; }
    	/// <summary>  
    	/// 接受者Id  
    	/// </summary>
        public string ReceiverId { get; set; }
    	/// <summary>  
    	/// 接受者编号  
    	/// </summary>
        public string ReceiverCode { get; set; }
    	/// <summary>  
    	/// 接受者姓名  
    	/// </summary>
        public string ReceiverName { get; set; }
    	/// <summary>  
    	/// 状态:0未处理1已处理  
    	/// </summary>
        public Nullable<int> State { get; set; }
    	/// <summary>  
    	/// 订单Id  
    	/// </summary>
        public string Title { get; set; }
    	/// <summary>  
    	/// 描述  
    	/// </summary>
        public string Comment { get; set; }
    	/// <summary>  
    	/// 创建时间  
    	/// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>  
    	/// 阅读时间  
    	/// </summary>
        public Nullable<System.DateTime> ReadTime { get; set; }
    }
}
