//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 管理角色表  
    /// </summary>
    public partial class Sys_Role
    {
    	/// <summary>  
    	/// 自增ID  
    	/// </summary>
        public int id { get; set; }
    	/// <summary>  
    	/// 角色名称  
    	/// </summary>
        public string role_name { get; set; }
    	/// <summary>  
    	/// 角色类型  
    	/// </summary>
        public Nullable<byte> role_type { get; set; }
    	/// <summary>  
    	/// 是否系统默认0否1是  
    	/// </summary>
        public Nullable<byte> is_sys { get; set; }
    	/// <summary>  
    	/// 所属的代理商Id  
    	/// </summary>
        public Nullable<int> agentId { get; set; }
    }
}
