//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// System.Data.SqlClient  
    /// </summary>
    public partial class VEmp
    {
    	/// <summary>  
    	///   
    	/// </summary>
        public string EmpId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string LoginName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Password { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string RealName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Sex { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Mobile { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> DepartmentId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> PositionId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<int> RoleId { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string EmpState { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string Comment { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public Nullable<System.DateTime> LastLogin { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string DepartmentName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string PositionName { get; set; }
    	/// <summary>  
    	///   
    	/// </summary>
        public string RoleName { get; set; }
    }
}
